My Project: de.datenkraken.datenkrake.DatabaseUnitTest Class Reference
de.datenkraken.datenkrake.DatabaseUnitTest Class Reference
Public Member Functions
void init ()
void closeDb ()
void insertAndLoadArticle ()
void singleQuerySourceReferences ()
void updateSource ()
void deletes ()
void foreignKeyConstraints ()
void singleArticle ()
Public Attributes
InstantTaskExecutorRule instantTaskExecutorRule = new InstantTaskExecutorRule()
Private Member Functions
List< Article > getRandomArticles (int number, Source source)
Article getRandomArticle (Source source)
Source getRandomSource ()
Private Attributes
AppDatabase db
Detailed Description
Instrumented test, which will execute on an Android device. Tests the Database.
Author
Daniel Thoma - danie.nosp@m.l.th.nosp@m.oma@s.nosp@m.tud..nosp@m.tu-da.nosp@m.rmst.nosp@m.adt.d.nosp@m.e
Definition at line 41 of file DatabaseUnitTest.java.
Member Function Documentation
closeDb()
void de.datenkraken.datenkrake.DatabaseUnitTest.closeDb ()
Definition at line 57 of file DatabaseUnitTest.java.
{
         db.close();
     }
deletes()
void de.datenkraken.datenkrake.DatabaseUnitTest.deletes ()
Definition at line 115 of file DatabaseUnitTest.java.
{
         Source source = getRandomSource();
         Source source1 = getRandomSource();
         List<Article> articles = getRandomArticles(10, source);
         List<Article> articles1 = getRandomArticles(5, source1);
         db.daoSource().insertOneSourceSync(source);
         db.daoSource().insertOneSourceSync(source1);
         db.daoArticle().insertOrUpdateAllArticleSync(articles);
         db.daoArticle().insertOrUpdateAllArticleSync(articles1);
         db.daoArticle().getAllArticleAsync().observeForever(new Observer<List<Article>>() {
             int counter = 0;
              @Override
              public void onChanged(List<Article> articles) {
                  if (articles == null) {
                      return;
                  }
                  switch (counter) {
                      case 0:
                          assertEquals(15, articles.size());
                          break;
                      case 1:
                          assertEquals(5, articles.size());
                         break;
                      case 2:
                          assertEquals(0, articles.size());
                          break;
                  }
                 counter++;
              }
         });
         db.daoArticle().deleteAllArticleBySourceUidSync(source.uid);
         db.daoArticle().deleteAllArticleCachedSync();
         db.daoSource().getAllSourceNotMarkedAsync().observeForever(new Observer<List<Source>>() {
             int counter = 0;
             @Override
             public void onChanged(List<Source> sources) {
                 if (sources == null) {
                     return;
                 }
                 switch (counter) {
                     case 0:
                         assertEquals(2, sources.size());
                         break;
                     case 1:
                         assertEquals(1, sources.size());
                         break;
                     case 2:
                         assertEquals(0, sources.size());
                         break;
                 }
                 counter++;
             }
         });
         db.daoSource().updateOneSourceMarkToDeleteSync(source);
         db.daoSource().updateOneSourceMarkToDeleteSync(source1);
     }
References de.datenkraken.datenkrake.db.AppDatabase.daoArticle(), de.datenkraken.datenkrake.db.AppDatabase.daoSource(), de.datenkraken.datenkrake.db.DaoArticle.deleteAllArticleBySourceUidSync(), de.datenkraken.datenkrake.db.DaoArticle.deleteAllArticleCachedSync(), de.datenkraken.datenkrake.db.DaoArticle.getAllArticleAsync(), de.datenkraken.datenkrake.db.DaoSource.getAllSourceNotMarkedAsync(), de.datenkraken.datenkrake.db.DaoSource.insertOneSourceSync(), de.datenkraken.datenkrake.db.DaoArticle.insertOrUpdateAllArticleSync(), de.datenkraken.datenkrake.model.Source.uid, and de.datenkraken.datenkrake.db.DaoSource.updateOneSourceMarkToDeleteSync().
foreignKeyConstraints()
void de.datenkraken.datenkrake.DatabaseUnitTest.foreignKeyConstraints ()
Definition at line 185 of file DatabaseUnitTest.java.
{
         Source source = getRandomSource();
         List<Article> articles = getRandomArticles(10, source);
         db.daoArticle().insertOrUpdateAllArticleSync(articles);
     }
References de.datenkraken.datenkrake.db.AppDatabase.daoArticle(), and de.datenkraken.datenkrake.db.DaoArticle.insertOrUpdateAllArticleSync().
getRandomArticle()
Article de.datenkraken.datenkrake.DatabaseUnitTest.getRandomArticle (Source source) private
Definition at line 216 of file DatabaseUnitTest.java.
{
         Random r = new Random();
         Article article = new Article();
         article.title = TestUtils.generateRandomString(30);
         article.imageUrl = Uri.parse(TestUtils.generateRandomLink(30));
         article.author = TestUtils.generateRandomString(10);
         article.publishedDate = new Date(r.nextLong());
         article.source = source;
         article.description = TestUtils.generateRandomString(100);
         article.content = TestUtils.generateRandomString(200);
         try {
             article.link = new URL(TestUtils.generateRandomLink(40));
         } catch (MalformedURLException e) {
             article.link = null;
             Timber.d(e, "generated flawed url for article link");
         }
         article.uid = Helper.generateArticleUid(article);
         return article;
     }
References de.datenkraken.datenkrake.model.Article.author, de.datenkraken.datenkrake.model.Article.content, de.datenkraken.datenkrake.model.Article.description, de.datenkraken.datenkrake.util.Helper.generateArticleUid(), de.datenkraken.datenkrake.model.Article.imageUrl, de.datenkraken.datenkrake.model.Article.link, de.datenkraken.datenkrake.model.Article.publishedDate, de.datenkraken.datenkrake.model.Article.source, de.datenkraken.datenkrake.model.Article.title, and de.datenkraken.datenkrake.model.Article.uid.
getRandomArticles()
List<Article> de.datenkraken.datenkrake.DatabaseUnitTest.getRandomArticles (int number, Source source) private
Definition at line 208 of file DatabaseUnitTest.java.
{
         Article[] articles = new Article[number];
         for(int i = 0; i < number; i++) {
             articles[i] = getRandomArticle(source);
         }
         return Arrays.asList(articles);
     }
getRandomSource()
Source de.datenkraken.datenkrake.DatabaseUnitTest.getRandomSource () private
Definition at line 236 of file DatabaseUnitTest.java.
{
         Source source = new Source();
         source.name =  TestUtils.generateRandomString(10);
         try {
             source.url = new URL(TestUtils.generateRandomLink(20));
         } catch (MalformedURLException e) {
             source.url = null;
             Timber.d(e, "generated flawed url for source");
         }
         source.deleted = false;
         source.uid = Helper.generateSourceUid(source);
         return source;
     }
References de.datenkraken.datenkrake.model.Source.deleted, de.datenkraken.datenkrake.util.Helper.generateSourceUid(), de.datenkraken.datenkrake.model.Source.name, de.datenkraken.datenkrake.model.Source.uid, and de.datenkraken.datenkrake.model.Source.url.
init()
void de.datenkraken.datenkrake.DatabaseUnitTest.init ()
Definition at line 49 of file DatabaseUnitTest.java.
{
         db = Room.inMemoryDatabaseBuilder(ApplicationProvider.getApplicationContext(), AppDatabase.class)
             .allowMainThreadQueries()
             .build();
         Timber.plant(new Timber.DebugTree());
     }
insertAndLoadArticle()
void de.datenkraken.datenkrake.DatabaseUnitTest.insertAndLoadArticle ()
Definition at line 62 of file DatabaseUnitTest.java.
{
         Source source = getRandomSource();
         List<Article> articles = this.getRandomArticles(20, source);
         db.daoSource().insertOneSourceSync(source);
         assertNotEquals(0, source.uid);
         db.daoArticle().insertOrUpdateAllArticleSync(articles);
         db.daoArticle().getAllArticleAsync().observeForever(observedArticles -> {
             if (observedArticles != null) {
                 assertEquals(articles.size(), observedArticles.size());
                 for (Article article : articles) {
                     assertTrue(observedArticles.contains(article));
                 }
             }
         });
     }
References de.datenkraken.datenkrake.db.AppDatabase.daoArticle(), de.datenkraken.datenkrake.db.AppDatabase.daoSource(), de.datenkraken.datenkrake.db.DaoArticle.getAllArticleAsync(), de.datenkraken.datenkrake.db.DaoSource.insertOneSourceSync(), de.datenkraken.datenkrake.db.DaoArticle.insertOrUpdateAllArticleSync(), and de.datenkraken.datenkrake.model.Source.uid.
singleArticle()
void de.datenkraken.datenkrake.DatabaseUnitTest.singleArticle ()
Definition at line 192 of file DatabaseUnitTest.java.
{
         Source source = getRandomSource();
         List<Article> articles = getRandomArticles(20, source);
         db.daoSource().insertOneSourceSync(source);
         db.daoArticle().insertOrUpdateAllArticleSync(articles);
         LiveData<Article> dbArticle = db.daoArticle().getOneArticleByArticleUidAsync(articles.get(15).uid);
         dbArticle.observeForever(article -> {
             if(article != null) {
                 assertEquals(articles.get(15), article);
             } else {
                 fail();
             }
         });
     }
References de.datenkraken.datenkrake.db.AppDatabase.daoArticle(), de.datenkraken.datenkrake.db.AppDatabase.daoSource(), de.datenkraken.datenkrake.db.DaoArticle.getOneArticleByArticleUidAsync(), de.datenkraken.datenkrake.db.DaoSource.insertOneSourceSync(), and de.datenkraken.datenkrake.db.DaoArticle.insertOrUpdateAllArticleSync().
singleQuerySourceReferences()
void de.datenkraken.datenkrake.DatabaseUnitTest.singleQuerySourceReferences ()
Definition at line 82 of file DatabaseUnitTest.java.
{
         Source source = getRandomSource();
         List<Article> articles = this.getRandomArticles(20, source);
         db.daoSource().insertOneSourceSync(source);
         db.daoArticle().insertOrUpdateAllArticleSync(articles);
         db.daoArticle().getAllArticleAsync().observeForever(observedArticles -> {
             if (observedArticles != null) {
                 Article current = observedArticles.get(0);
                 for (int i = 1; i < observedArticles.size(); i++) {
                     assertSame(current.source, observedArticles.get(i).source);
                 }
             }
         });
     }
References de.datenkraken.datenkrake.db.AppDatabase.daoArticle(), de.datenkraken.datenkrake.db.AppDatabase.daoSource(), de.datenkraken.datenkrake.db.DaoArticle.getAllArticleAsync(), de.datenkraken.datenkrake.db.DaoSource.insertOneSourceSync(), de.datenkraken.datenkrake.db.DaoArticle.insertOrUpdateAllArticleSync(), and de.datenkraken.datenkrake.model.Article.source.
updateSource()
void de.datenkraken.datenkrake.DatabaseUnitTest.updateSource ()
Definition at line 100 of file DatabaseUnitTest.java.
{
         Source source = getRandomSource();
         db.daoSource().insertOneSourceSync(source);
         source.name = TestUtils.generateRandomString(30);
         db.daoSource().updateOneSourceSync(source);
         db.daoSource().getOneSourceByIdAsync(source.uid).observeForever(observedSource -> {
             if (observedSource != null) {
                 assertEquals(source, observedSource);
             }
         });
     }
References de.datenkraken.datenkrake.db.AppDatabase.daoSource(), de.datenkraken.datenkrake.db.DaoSource.getOneSourceByIdAsync(), de.datenkraken.datenkrake.db.DaoSource.insertOneSourceSync(), de.datenkraken.datenkrake.model.Source.name, de.datenkraken.datenkrake.model.Source.uid, and de.datenkraken.datenkrake.db.DaoSource.updateOneSourceSync().
Member Data Documentation
db
AppDatabase de.datenkraken.datenkrake.DatabaseUnitTest.db private
Definition at line 43 of file DatabaseUnitTest.java.
instantTaskExecutorRule
InstantTaskExecutorRule de.datenkraken.datenkrake.DatabaseUnitTest.instantTaskExecutorRule = new InstantTaskExecutorRule()
Definition at line 46 of file DatabaseUnitTest.java.
The documentation for this class was generated from the following file:
C:/Users/Masel/OneDrive/Dokumente/git/app/app/src/androidTest/java/de/datenkraken/datenkrake/DatabaseUnitTest.java