My Project: de.datenkraken.datenkrake.TestQuery Class Reference
de.datenkraken.datenkrake.TestQuery Class Reference
Classes
class Builder
class Data
class Test
Public Member Functions
TestQuery ()
String operationId ()
String queryDocument ()
TestQuery.Data wrapData (TestQuery.Data data)
Operation.Variables variables ()
ResponseFieldMapper< TestQuery.Data > responseFieldMapper ()
OperationName name ()
Response< TestQuery.Data > parse (@NotNull final BufferedSource source, @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException
Response< TestQuery.Data > parse (@NotNull final BufferedSource source) throws IOException
Static Public Member Functions
static Builder builder ()
Static Public Attributes
static final String OPERATION_ID = "3bbe988877c7b59f6de148254bb1cb66a9d631854735d4bd4ac32ef82d0ec675"
static final String QUERY_DOCUMENT
static final OperationName OPERATION_NAME
Private Attributes
final Operation.Variables variables
Detailed Description
Definition at line 32 of file TestQuery.java.
Constructor & Destructor Documentation
TestQuery()
de.datenkraken.datenkrake.TestQuery.TestQuery ()
Definition at line 54 of file TestQuery.java.
                      {
     this.variables = Operation.EMPTY_VARIABLES;
   }
References de.datenkraken.datenkrake.TestQuery.variables.
Referenced by de.datenkraken.datenkrake.TestQuery.Builder.build().
Member Function Documentation
builder()
static Builder de.datenkraken.datenkrake.TestQuery.builder () static
Definition at line 83 of file TestQuery.java.
{
     return new Builder();
   }
name()
OperationName de.datenkraken.datenkrake.TestQuery.name ()
Definition at line 88 of file TestQuery.java.
{
     return OPERATION_NAME;
   }
References de.datenkraken.datenkrake.TestQuery.OPERATION_NAME.
operationId()
String de.datenkraken.datenkrake.TestQuery.operationId ()
Definition at line 59 of file TestQuery.java.
{
     return OPERATION_ID;
   }
References de.datenkraken.datenkrake.TestQuery.OPERATION_ID.
parse() [1/2]
Response<TestQuery.Data> de.datenkraken.datenkrake.TestQuery.parse (@NotNull final BufferedSource source) throws IOException
Definition at line 101 of file TestQuery.java.
{
     return parse(source, ScalarTypeAdapters.DEFAULT);
   }
References de.datenkraken.datenkrake.TestQuery.parse().
parse() [2/2]
Response<TestQuery.Data> de.datenkraken.datenkrake.TestQuery.parse (@NotNull final BufferedSource source, @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException
Definition at line 94 of file TestQuery.java.
{
     return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
   }
Referenced by de.datenkraken.datenkrake.TestQuery.parse().
queryDocument()
String de.datenkraken.datenkrake.TestQuery.queryDocument ()
Definition at line 64 of file TestQuery.java.
{
     return QUERY_DOCUMENT;
   }
References de.datenkraken.datenkrake.TestQuery.QUERY_DOCUMENT.
responseFieldMapper()
ResponseFieldMapper<TestQuery.Data> de.datenkraken.datenkrake.TestQuery.responseFieldMapper ()
Definition at line 79 of file TestQuery.java.
{
     return new Data.Mapper();
   }
variables()
Operation.Variables de.datenkraken.datenkrake.TestQuery.variables ()
Definition at line 74 of file TestQuery.java.
{
     return variables;
   }
References de.datenkraken.datenkrake.TestQuery.variables.
wrapData()
TestQuery.Data de.datenkraken.datenkrake.TestQuery.wrapData (TestQuery.Data data)
Definition at line 69 of file TestQuery.java.
{
     return data;
   }
Member Data Documentation
OPERATION_ID
final String de.datenkraken.datenkrake.TestQuery.OPERATION_ID = "3bbe988877c7b59f6de148254bb1cb66a9d631854735d4bd4ac32ef82d0ec675" static
Definition at line 33 of file TestQuery.java.
Referenced by de.datenkraken.datenkrake.TestQuery.operationId().
OPERATION_NAME
final OperationName de.datenkraken.datenkrake.TestQuery.OPERATION_NAME static
Initial value:
= new OperationName() {
    @Override
    public String name() {
      return "TestQuery";
    }
  }
Definition at line 45 of file TestQuery.java.
Referenced by de.datenkraken.datenkrake.TestQuery.name().
QUERY_DOCUMENT
final String de.datenkraken.datenkrake.TestQuery.QUERY_DOCUMENT static
Initial value:
= QueryDocumentMinifier.minify(
    "query TestQuery {\n"
        + "  test {\n"
        + "    __typename\n"
        + "    data\n"
        + "    end\n"
        + "  }\n"
        + "}"
  )
Definition at line 35 of file TestQuery.java.
Referenced by de.datenkraken.datenkrake.TestQuery.queryDocument().
variables
final Operation.Variables de.datenkraken.datenkrake.TestQuery.variables private
Definition at line 52 of file TestQuery.java.
Referenced by de.datenkraken.datenkrake.TestQuery.TestQuery(), and de.datenkraken.datenkrake.TestQuery.variables().
The documentation for this class was generated from the following file:
C:/Users/Masel/OneDrive/Dokumente/git/app/app/src/test/java/de/datenkraken/datenkrake/TestQuery.java