My Project: de.datenkraken.datenkrake.DownloadFeedUnitTest Class Reference
de.datenkraken.datenkrake.DownloadFeedUnitTest Class Reference
Classes
class testOkHttpFeed
Public Member Functions
void testDownloadFeedParse ()
void testFeedNotSupported ()
void testFeedCorrupted ()
void testSiteExisting ()
Public Attributes
TimberTestRule logAllAlwaysRule = TimberTestRule.logAllAlways()
Detailed Description
Definition at line 37 of file DownloadFeedUnitTest.java.
Member Function Documentation
testDownloadFeedParse()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testDownloadFeedParse ()
Definition at line 44 of file DownloadFeedUnitTest.java.
{
         Source source = new Source();
         MockWebServer server = new MockWebServer();
         Context mockApplicationContext = mock(Context.class);
         Resources mockContextResources = mock(Resources.class);
         when(mockApplicationContext.getResources()).thenReturn(mockContextResources);
         when(mockContextResources.getString(anyInt())).thenReturn(server.url("/").toString());
         TaskDistributor.setup(mockApplicationContext);
         try {
             server.enqueue(new MockResponse().setResponseCode(200).setBody(TestUtils.getResource("sampledata/FeedResponses/RSS0.91.txt")));
             server.enqueue(new MockResponse().setResponseCode(200).setBody(TestUtils.getResource("sampledata/FeedResponses/RSS1.0.txt")));
             server.enqueue(new MockResponse().setResponseCode(200).setBody(TestUtils.getResource("sampledata/FeedResponses/RSS2.0.txt")));
             server.enqueue(new MockResponse().setResponseCode(200).setBody(TestUtils.getResource("sampledata/FeedResponses/ATOM1.0.txt")));
         } catch (IOException e) {
             assert false;
         }
         Article article = new Article();
         article.title = "Title";
         article.description = "Description";
         article.content = "Content";
         article.source = source;
         try {
             article.link = new URL("https://www.test.de/");
         } catch (MalformedURLException e) {
             article.link = null;
         }
         try {
             article.publishedDate = new SimpleDateFormat("EEE, dd MMM yyyy hh:mm:ss Z", Locale.US).parse("Sun, 01 Dec 2019 15:05:00 +0100");
         } catch (ParseException pe) {
             Timber.e(pe,"parse error");
         }
         source.url = server.url("rssfeeds").url();
         article.uid = Helper.generateArticleUid(article);
         testOkHttpFeed feed = new testOkHttpFeed(source);
         feed.source = source;
         feed.request(); // RSS 0.91
         assert (feed.articles.size() == 1);
         assert feed.articles.get(0).equals(article);
         article.author = "Daniel Thoma";
         article.uid = Helper.generateArticleUid(article);
         feed.request(); // RSS 1.0
         assert (feed.articles.size() == 1);
         assert feed.articles.get(0).equals(article);
         article.author = null;
         article.uid = Helper.generateArticleUid(article);
         feed.request(); // RSS 2.0
         assert (feed.articles.size() == 1);
         assert feed.articles.get(0).equals(article);
         article.title = "Datenkrake frisst Menschen";
         article.author = "Daniel Thoma";
         article.content = null;
         article.uid = Helper.generateArticleUid(article);
         feed.request(); // ATOM1.0
         assert (feed.articles.size() == 1);
         assert feed.articles.get(0).equals(article);
     }
References de.datenkraken.datenkrake.model.Article.author, de.datenkraken.datenkrake.model.Article.content, de.datenkraken.datenkrake.model.Article.description, de.datenkraken.datenkrake.util.Helper.generateArticleUid(), de.datenkraken.datenkrake.model.Article.link, de.datenkraken.datenkrake.model.Article.publishedDate, de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed.request(), de.datenkraken.datenkrake.network.TaskDistributor.setup(), de.datenkraken.datenkrake.model.Article.source, de.datenkraken.datenkrake.controller.feedupdater.rss.OkHttpFeed.source, de.datenkraken.datenkrake.model.Article.title, de.datenkraken.datenkrake.model.Article.uid, and de.datenkraken.datenkrake.model.Source.url.
testFeedCorrupted()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testFeedCorrupted ()
Definition at line 176 of file DownloadFeedUnitTest.java.
{
         MockWebServer server = new MockWebServer();
         Context mockApplicationContext = mock(Context.class);
         Resources mockContextResources = mock(Resources.class);
         when(mockApplicationContext.getResources()).thenReturn(mockContextResources);
         when(mockContextResources.getString(anyInt())).thenReturn(server.url("/").toString());
         TaskDistributor.setup(mockApplicationContext);
         try {
             server.enqueue(new MockResponse().setResponseCode(200).setBody(TestUtils.getResource("sampledata/FeedResponses/corrupted.txt")));
         } catch (IOException e) {
             assert false;
         }
         Source source = new Source();
         source.url = server.url("rssfeeds").url();
         new OkHttpFeed(source) {
             @Override
             public void onSuccessfulParsed(@NotNull List<Article> articles) {
                 assert false;
             }
             @Override
             public void onFeedException(@NotNull FeedException e) {
                 assert true;
             }
             @Override
             public void onFailure(@NotNull Call call, @NotNull IOException e) {
                 assert false;
             }
             @Override
             public void request() {
                 TaskDistributor.getInstance().synchronousRequest(this);
             }
         }.request();
     }
References de.datenkraken.datenkrake.network.TaskDistributor.getInstance(), de.datenkraken.datenkrake.network.TaskDistributor.setup(), de.datenkraken.datenkrake.network.TaskDistributor.synchronousRequest(), and de.datenkraken.datenkrake.model.Source.url.
testFeedNotSupported()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testFeedNotSupported ()
Definition at line 137 of file DownloadFeedUnitTest.java.
{
         MockWebServer server = new MockWebServer();
         String path = "sampledata/FeedResponses/OPML1.0.txt";
         Context mockApplicationContext = mock(Context.class);
         Resources mockContextResources = mock(Resources.class);
         when(mockApplicationContext.getResources()).thenReturn(mockContextResources);
         when(mockContextResources.getString(anyInt())).thenReturn(server.url("/").toString());
         TaskDistributor.setup(mockApplicationContext);
         try {
             server.enqueue(new MockResponse().setResponseCode(200).setBody(TestUtils.getResource(path)));
         } catch (IOException e) {
             assert false;
         }
         Source source = new Source();
         source.url = server.url(path).url();
         new OkHttpFeed(source) {
             @Override
             public void onSuccessfulParsed(@NotNull List<Article> articles) {
                 assert false;
             }
             @Override
             public void onFeedException(@NotNull FeedException e) {
                 assert e.getClass().equals(UnsupportedVersionException.class);
             }
             @Override
             public void onFailure(@NotNull Call call, @NotNull IOException e) {
                 assert false;
             }
         }.request();
     }
References de.datenkraken.datenkrake.network.clients.okhttp.OkHttpTask.request(), de.datenkraken.datenkrake.network.TaskDistributor.setup(), and de.datenkraken.datenkrake.model.Source.url.
testSiteExisting()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testSiteExisting ()
Definition at line 219 of file DownloadFeedUnitTest.java.
{
         Context mockApplicationContext = mock(Context.class);
         Resources mockContextResources = mock(Resources.class);
         when(mockApplicationContext.getResources()).thenReturn(mockContextResources);
         when(mockContextResources.getString(anyInt())).thenReturn("");
         TaskDistributor.setup(mockApplicationContext);
         Source source = new Source();
         try {
             source.url = new URL("http://ksdlafkloajsdfolkjad.com");
         } catch (MalformedURLException e) {
             Timber.e("Malformed URL!");
         }
         new OkHttpFeed(source) {
             @Override
             public void onSuccessfulParsed(@NotNull List<Article> articles) {
                 assert false;
             }
             @Override
             public void onFeedException(@NotNull FeedException e) {
                 assert false;
             }
             @Override
             public void onFailure(@NotNull Call call, @NotNull IOException e) {
                 assert true;
             }
             @Override
             public void request() {
                 TaskDistributor.getInstance().synchronousRequest(this);
             }
         }.request();
     }
References de.datenkraken.datenkrake.network.TaskDistributor.getInstance(), de.datenkraken.datenkrake.network.TaskDistributor.setup(), de.datenkraken.datenkrake.network.TaskDistributor.synchronousRequest(), and de.datenkraken.datenkrake.model.Source.url.
Member Data Documentation
logAllAlwaysRule
TimberTestRule de.datenkraken.datenkrake.DownloadFeedUnitTest.logAllAlwaysRule = TimberTestRule.logAllAlways()
Definition at line 41 of file DownloadFeedUnitTest.java.
The documentation for this class was generated from the following file:
C:/Users/Masel/OneDrive/Dokumente/git/app/app/src/test/java/de/datenkraken/datenkrake/DownloadFeedUnitTest.java