My Project: de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed Class Reference
de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed Class Reference
Public Member Functions
testOkHttpFeed (Source source)
void onSuccessfulParsed (@NotNull List< Article > articles)
void onFeedException (@NotNull FeedException e)
void onFailure (@NotNull Call call, @NotNull IOException e)
void request ()
Public Member Functions inherited from de.datenkraken.datenkrake.controller.feedupdater.rss.OkHttpFeed
OkHttpFeed (Source source)
final Request getRequest ()
final void onResponse (@NotNull Call call, @NotNull Response response) throws IOException
Public Member Functions inherited from de.datenkraken.datenkrake.network.clients.okhttp.OkHttpTask
final void cancel ()
final Class< OkHttp > processedBy ()
Additional Inherited Members
Public Attributes inherited from de.datenkraken.datenkrake.controller.feedupdater.rss.OkHttpFeed
Source source
Public Attributes inherited from de.datenkraken.datenkrake.network.clients.okhttp.OkHttpTask
Call call
Detailed Description
Definition at line 108 of file DownloadFeedUnitTest.java.
Constructor & Destructor Documentation
testOkHttpFeed()
de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed.testOkHttpFeed (Source source)
Definition at line 111 of file DownloadFeedUnitTest.java.
{
             super(source);
         }
References de.datenkraken.datenkrake.controller.feedupdater.rss.OkHttpFeed.source.
Member Function Documentation
onFailure()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed.onFailure (@NotNull Call call, @NotNull IOException e)
Definition at line 126 of file DownloadFeedUnitTest.java.
{
             assert false;
         }
onFeedException()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed.onFeedException (@NotNull FeedException e)
Gets called when this de.datenkraken.datenkrake.network.ITask was not able to parse the Response.
Parameters
e FeedException to be displayed.
Reimplemented from de.datenkraken.datenkrake.controller.feedupdater.rss.OkHttpFeed.
Definition at line 121 of file DownloadFeedUnitTest.java.
{
             assert false;
         }
onSuccessfulParsed()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed.onSuccessfulParsed (@NotNull List< Article > articles)
Gets called when the downloaded feed could be parsed into an Article list.
Parameters
articles list of Articles.
Reimplemented from de.datenkraken.datenkrake.controller.feedupdater.rss.OkHttpFeed.
Definition at line 116 of file DownloadFeedUnitTest.java.
{
             this.articles = articles;
         }
request()
void de.datenkraken.datenkrake.DownloadFeedUnitTest.testOkHttpFeed.request ()
Requests to enqueue this task in the TaskDistributor.
Reimplemented from de.datenkraken.datenkrake.network.clients.okhttp.OkHttpTask.
Definition at line 131 of file DownloadFeedUnitTest.java.
{
             TaskDistributor.getInstance().synchronousRequest(this);
         }
References de.datenkraken.datenkrake.network.TaskDistributor.getInstance(), and de.datenkraken.datenkrake.network.TaskDistributor.synchronousRequest().
Referenced by de.datenkraken.datenkrake.DownloadFeedUnitTest.testDownloadFeedParse().
The documentation for this class was generated from the following file:
C:/Users/Masel/OneDrive/Dokumente/git/app/app/src/test/java/de/datenkraken/datenkrake/DownloadFeedUnitTest.java